No module selected error added

diff --git a/bin/ak b/bin/ak
--- a/bin/ak
+++ b/bin/ak
@@ -57,6 +57,12 @@ case "$1" in
         shift
         subcmd="$AK_MODULESDIR/$(echo $1 | sed -e 's/ /-/g')"
         shift
+        if [ -z $* ] || [ ! -n "$*" ]
+        then
+            logit "ERROR" "No module selected"
+            ls -1 $AK_MODULESDIR
+            exit 1
+        fi
         subargs="$*"
         $subcmd $subargs
         _ak_exit_program $? "$subcmd module finished";
