Spacing adjustment

diff --git a/bin/ak-articles b/bin/ak-articles
--- a/bin/ak-articles
+++ b/bin/ak-articles
@@ -3,16 +3,16 @@ ZARTICLESDIR="$AK_WORKDIR/articles"
 TEMP="/tmp/aktmp"
 echo $ZARTICLESDIR
 if [ ! -d $ZARTICLESDIR ]; then
-	mkdir $ZARTICLESDIR
-	cd $ZARTICLESDIR
-	git init
-	echo "Articles repository" > README
-	echo "Qmetc" >> README
-	git add README
-	git commit -m "Initiated articles repository"
-	echo "zarticlesdir created along with git repo"
+    mkdir $ZARTICLESDIR
+    cd $ZARTICLESDIR
+    #git init
+    echo "Articles repository" > README
+    echo "Qmetc" >> README
+    #git add README
+    #git commit -m "Initiated articles repository"
+    logit "INFO" "zarticlesdir created"
 else
-	echo "zarticlesdir found"
+    logit "INFO" "zarticlesdir found"
 fi
 
 _ak_modules_articles_create(){
@@ -36,55 +36,55 @@ _ak_modules_articles_create(){
 	# rm -rf $TEMP 
 }
 _ak_modules_articles_index(){
-	FILES="$(ls -1 $ZARTICLESDIR)"
-	i=0
-	for FILE in $FILES
-	do
-		DATE=$(echo $FILE | cut -d - -f 1 | awk '{print $1}')
-		TITLE=$(head -n 1 $ZARTICLESDIR/$FILE)
-		echo $i \| $DATE \| $TITLE
-		let i+=1
-	done	
+    FILES="$(ls -1 $ZARTICLESDIR)"
+    i=0
+    for FILE in $FILES
+    do
+        DATE=$(echo $FILE | cut -d - -f 1 | awk '{print $1}')
+        TITLE=$(head -n 1 $ZARTICLESDIR/$FILE)
+        echo $i \| $DATE \| $TITLE
+        let i+=1
+    done
 }
 _ak_modules_articles_title(){
 	echo	ak-articles-cli
 	echo "--------------"
 }
 _ak_modules_articles_import(){
-	echo "#TODO"
-	if [ ! -z $1 ]
-	then
-		if [ ! -d $1 ]
-		then
-			echo "Folder does not exists"
-			exit 4
-		else
-			echo "Folder $1 exists"
-			fl="$(ls -1 $1)"
-			for f in $fl
-			do
-				_ak_modules_articles_add $1/$f
-			done
-		fi
-	else
-		echo "No value"
-		exit 6
-	fi
-	exit 224
+    echo "#TODO"
+    if [ ! -z $1 ]
+    then
+        if [ ! -d $1 ]
+        then
+            echo "Folder does not exists"
+            exit 4
+        else
+            echo "Folder $1 exists"
+            fl="$(ls -1 $1)"
+            for f in $fl
+            do
+                _ak_modules_articles_add $1/$f
+            done
+        fi
+    else
+        echo "No value"
+        exit 6
+    fi
+    exit 224
 }
 _ak_modules_articles_add(){
     TEMP="$(ak-tempassin)"
     cd $TEMP
-	if [ -f $1 ]; then
-		FILE="$1"
-		echo "Adding articles from " $FILE
-		DATETIME=$(echo $FILE | cut -d - -f 1 | awk '{print $1}')
-		TITLE=$(head -n 1 $FILE)
-		FILE_IPFS_HASH=$(ak-ipfs-add $FILE)
-		FILE_SIGN_FILE=$FILE".asc"
-		gpg2 --homedir $AK_GPGHOME --detach-sign --sign-with $AK_FINGERPRINT --armor --output $FILE_SIGN_FILE $FILE
-		FILE_SIGNATURE=$(ak-ipfs-add $FILE_SIGN_FILE)
-		cat > data <<EOF
+    if [ -f $1 ]; then
+        FILE="$1"
+        echo "Adding articles from " $FILE
+        DATETIME=$(echo $FILE | cut -d - -f 1 | awk '{print $1}')
+        TITLE=$(head -n 1 $FILE)
+        FILE_IPFS_HASH=$(ak-ipfs-add $FILE)
+        FILE_SIGN_FILE=$FILE".asc"
+        gpg2 --homedir $AK_GPGHOME --detach-sign --sign-with $AK_FINGERPRINT --armor --output $FILE_SIGN_FILE $FILE
+        FILE_SIGNATURE=$(ak-ipfs-add $FILE_SIGN_FILE)
+        cat > data <<EOF
 {
    "datetime":"$DATETIME",
    "title":"$TITLE",
@@ -93,39 +93,37 @@ _ak_modules_articles_add(){
    "detach":"$FILE_SIGNATURE"
 }
 EOF
-	else
-		echo "File $FILE doesn't exist";
-		exit 2
-	fi
+    else
+        echo "File $FILE doesn't exist";
+        exit 2
+    fi
     ak-zblock-pack "articles/add" $(pwd)/data
-	if [ $? == 0 ]
-	then
-		echo "Articles added successfully"
-	else
-		echo "error??"
-		exit 1
-	fi
+    if [ $? == 0 ]
+    then
+        echo "Articles added successfully"
+    else
+        echo "error??"
+        exit 1
+    fi
 }
 _ak_modules_articles_usage(){
-	echo "#TODO"
-	echo "All you need to know is that there are two options available:"
-	echo "help		Prints this help message"
-	echo "index		Prints an indexed table of your articles files"
-	echo "import <file>	#TODO"
-	echo "add <file>	Creates a data file from the articles file you point to"
-	echo "create		Vim is going to pop up, you will write and save your"
-	echo "                  articlesletter and it's going to be saved"
-	exit 0
+    echo "    -h, --help        Prints this help message"
+    echo "    index             Prints an indexed table of your articles files"
+    echo "    import <file>     #TODO"
+    echo "    add <file>        Creates a data file from the articles file you point to"
+    echo "    create            Vim is going to pop up, you will write and save your"
+    echo "                      articlesletter and it's going to be saved"
+    exit 0
 }
 _ak_modules_articles_title
 if [ ! -z $1 ]; then
-	case $1 in
-		help) _ak_modules_articles_usage; exit;;
-		index) _ak_modules_articles_index; exit;;
-		import) _ak_modules_articles_import $2; exit;;
-		add) _ak_modules_articles_add $2; exit;;
-		create) _ak_modules_articles_create; exit;;
-		* ) _ak_modules_articles_usage;;
-	esac
+    case $1 in
+        -h | --help) _ak_modules_articles_usage; exit;;
+        index) _ak_modules_articles_index; exit;;
+        import) _ak_modules_articles_import $2; exit;;
+        add) _ak_modules_articles_add $2; exit;;
+        create) _ak_modules_articles_create; exit;;
+        * ) _ak_modules_articles_usage;;
+    esac
 else _ak_modules_articles_usage
 fi
diff --git a/bin/ak-categories b/bin/ak-categories
--- a/bin/ak-categories
+++ b/bin/ak-categories
@@ -4,77 +4,77 @@ PROGRAM="$(basename $0)"
 
 echo $AK_CATEGORIES
 if [ ! -d $AK_CATEGORIES ]; then
-	mkdir $AK_CATEGORIES
-	cd $AK_CATEGORIES
-	echo "AK_CATEGORIES created"
+    mkdir $AK_CATEGORIES
+    cd $AK_CATEGORIES
+    echo "AK_CATEGORIES created"
 else
-	echo "AK_CATEGORIES found"
+    echo "AK_CATEGORIES found"
 fi
 
 _ak_modules_categories_create(){
     TEMP="$(ak-tempassin)"
     cd $TEMP
-	export NEWS_FILE="$(date +%Y%m%d_%H%M%S)"
-	vi $NEWS_FILE
-	echo "Renaming..."
-	TITLE="$(head -n 1 $NEWS_FILE)"
-	TO_FILE=$NEWS_FILE-$(echo $TITLE | tr '[:upper:]' '[:lower:]' | sed -e 's/ /\_/g' )
-	IPFS_FILE=$(ak-ipfs-add $NEWS_FILE)
-	mv $NEWS_FILE $AK_CATEGORIES/$TO_FILE
-	sed -e 's,Qm.*,'"$IPFS_FILE"',g' $AK_CATEGORIES/README
-	_ak_modules_categories_add $AK_CATEGORIES/$TO_FILE
-	cd $AK_CATEGORIES
+    export NEWS_FILE="$(date +%Y%m%d_%H%M%S)"
+    vi $NEWS_FILE
+    echo "Renaming..."
+    TITLE="$(head -n 1 $NEWS_FILE)"
+    TO_FILE=$NEWS_FILE-$(echo $TITLE | tr '[:upper:]' '[:lower:]' | sed -e 's/ /\_/g' )
+    IPFS_FILE=$(ak-ipfs-add $NEWS_FILE)
+    mv $NEWS_FILE $AK_CATEGORIES/$TO_FILE
+    sed -e 's,Qm.*,'"$IPFS_FILE"',g' $AK_CATEGORIES/README
+    _ak_modules_categories_add $AK_CATEGORIES/$TO_FILE
+    cd $AK_CATEGORIES
 }
 _ak_modules_categories_index(){
-	FILES="$(ls -1 $AK_CATEGORIES)"
-	i=0
-	for FILE in $FILES
-	do
-		DATE=$(echo $FILE | cut -d - -f 1 | awk '{print $1}')
-		TITLE=$(head -n 1 $AK_CATEGORIES/$FILE)
-		echo $i \| $DATE \| $TITLE
-		let i+=1
-	done	
+    FILES="$(ls -1 $AK_CATEGORIES)"
+    i=0
+    for FILE in $FILES
+    do
+        DATE=$(echo $FILE | cut -d - -f 1 | awk '{print $1}')
+        TITLE=$(head -n 1 $AK_CATEGORIES/$FILE)
+        echo $i \| $DATE \| $TITLE
+        let i+=1
+    done
 }
 _ak_modules_categories_title(){
     echo "$PROGRAM"
 }
 
 _ak_modules_categories_import(){
-	echo "#TODO"
-	if [ ! -z $1 ]
-	then
-		if [ ! -d $1 ]
-		then
-			echo "Folder does not exists"
-			exit 4
-		else
-			echo "Folder $1 exists"
-			fl="$(ls -1 $1)"
-			for f in $fl
-			do
-				_ak_modules_categories_add $1/$f
-			done
-		fi
-	else
-		echo "No value"
-		exit 6
-	fi
-	exit 224
+    echo "#TODO"
+    if [ ! -z $1 ]
+    then
+        if [ ! -d $1 ]
+        then
+            echo "Folder does not exists"
+            exit 4
+        else
+            echo "Folder $1 exists"
+            fl="$(ls -1 $1)"
+            for f in $fl
+            do
+                _ak_modules_categories_add $1/$f
+            done
+        fi
+    else
+        echo "No value"
+        exit 6
+    fi
+    exit 224
 }
 _ak_modules_categories_add(){
     TEMP="$(ak-tempassin)"
     cd $TEMP
-	if [ -f $1 ]; then
-		FILE="$1"
-		echo "Adding news from " $FILE
-		DATETIME=$(echo $FILE | cut -d - -f 1 | awk '{print $1}')
-		TITLE=$(head -n 1 $FILE)
-		FILE_IPFS_HASH=$(ak-ipfs-add $FILE)
-		FILE_SIGN_FILE=$FILE".asc"
-		gpg2 --homedir $AK_GPGHOME --detach-sign --sign-with $AK_FINGERPRINT --armor --output $FILE_SIGN_FILE $FILE
-		FILE_SIGNATURE=$(ak-ipfs-add $FILE_SIGN_FILE)
-		cat > data <<EOF
+    if [ -f $1 ]; then
+        FILE="$1"
+        echo "Adding news from " $FILE
+        DATETIME=$(echo $FILE | cut -d - -f 1 | awk '{print $1}')
+        TITLE=$(head -n 1 $FILE)
+        FILE_IPFS_HASH=$(ak-ipfs-add $FILE)
+        FILE_SIGN_FILE=$FILE".asc"
+        gpg2 --homedir $AK_GPGHOME --detach-sign --sign-with $AK_FINGERPRINT --armor --output $FILE_SIGN_FILE $FILE
+        FILE_SIGNATURE=$(ak-ipfs-add $FILE_SIGN_FILE)
+        cat > data <<EOF
 {
    "datetime":"$DATETIME",
    "title":"$TITLE",
@@ -83,18 +83,18 @@ _ak_modules_categories_add(){
    "detach":"$FILE_SIGNATURE"
 }
 EOF
-	else
-		echo "File $FILE doesn't exist";
-		exit 2
-	fi
+    else
+        echo "File $FILE doesn't exist";
+        exit 2
+    fi
     ak-zblock-pack "news/add" $(pwd)/data
-	if [ $? == 0 ]
-	then
-		echo "News added successfully"
-	else
-		echo "error??"
-		exit 1
-	fi
+    if [ $? == 0 ]
+    then
+        echo "News added successfully"
+    else
+        echo "error??"
+        exit 1
+    fi
 }
 _ak_modules_categories_usage(){
 	echo "#TODO"
@@ -115,7 +115,7 @@ if [ ! -z $1 ]; then
 		import) _ak_modules_categories_import $2; exit;;
 		add) _ak_modules_categories_add $2; exit;;
         create) _ak_modules_categories_create; exit;;
-		* ) _ak_modules_categories_usage;;
-	esac
+        * ) _ak_modules_categories_usage;;
+    esac
 else _ak_modules_categories_usage
 fi
diff --git a/bin/ak-comments b/bin/ak-comments
--- a/bin/ak-comments
+++ b/bin/ak-comments
@@ -6,9 +6,9 @@ logit(){
 ZCOMMENTSDIR="$AK_WORKDIR/comments"
 TEMP="/tmp/aktmp"
 if [ ! -d $ZCOMMENTSDIR ]; then
-	mkdir $ZCOMMENTSDIR
-	cd $ZCOMMENTSDIR
-	ak-logthis "[INFO]" "zcommentsdir created"
+    mkdir $ZCOMMENTSDIR
+    cd $ZCOMMENTSDIR
+    logit "INFO" "zcommentsdir created"
 else
     logit "INFO" "zcommentsdir found"
 fi
@@ -40,43 +40,43 @@ _ak_modules_comments_create(){
 }
 
 _ak_modules_comments_index(){
-	FILES="$(ls -1 $ZCOMMENTSDIR)"
-	i=0
-	for FILE in $FILES
-	do
-		DATE=$(echo $FILE | cut -d - -f 1 | awk '{print $1}')
-		TITLE=$(head -n 1 $ZCOMMENTSDIR/$FILE)
-		echo $i \| $DATE \| $TITLE
-		let i+=1
-	done	
+    FILES="$(ls -1 $ZCOMMENTSDIR)"
+    i=0
+    for FILE in $FILES
+    do
+        DATE=$(echo $FILE | cut -d - -f 1 | awk '{print $1}')
+        TITLE=$(head -n 1 $ZCOMMENTSDIR/$FILE)
+        echo $i \| $DATE \| $TITLE
+        let i+=1
+    done
 }
 _ak_modules_comments_title(){
-	echo comments
+    echo comments
 }
 _ak_modules_comments_add(){
     TEMP="$(ak-tempassin)"
     cd $TEMP
-	if [ -f "$ZCOMMENTSDIR/$1" ]; then
-		FILE=$ZCOMMENTSDIR/$1
-		echo "Adding comments from " $FILE
-		DATETIME="$1"
-		FILE_IPFS_HASH=$(ak-ipfs-add $FILE)
-		FILE_SIGN_FILE=$FILE".asc"
-		gpg2 --homedir $AK_GPGHOME --detach-sign --sign-with $AK_FINGERPRINT --armor --output $FILE_SIGN_FILE $FILE
-		FILE_SIGNATURE=$(ak-ipfs-add $FILE_SIGN_FILE)
-		printf '{"datetime":"%s","ipfs":"%s","detach":"%s"}' $DATETIME $FILE_IPFS_HASH $FILE_SIGNATURE > data
-	else
-		echo "File $FILE doesn't exist";
-		exit 2
-	fi
+    if [ -f "$ZCOMMENTSDIR/$1" ]; then
+        FILE=$ZCOMMENTSDIR/$1
+        echo "Adding comments from " $FILE
+        DATETIME="$1"
+        FILE_IPFS_HASH=$(ak-ipfs-add $FILE)
+        FILE_SIGN_FILE=$FILE".asc"
+        gpg2 --homedir $AK_GPGHOME --detach-sign --sign-with $AK_FINGERPRINT --armor --output $FILE_SIGN_FILE $FILE
+        FILE_SIGNATURE=$(ak-ipfs-add $FILE_SIGN_FILE)
+        printf '{"datetime":"%s","ipfs":"%s","detach":"%s"}' $DATETIME $FILE_IPFS_HASH $FILE_SIGNATURE > data
+    else
+        echo "File $FILE doesn't exist";
+        exit 2
+    fi
     REFERENCE="$(ak-zblock-pack "comments/add" $(pwd)/data)"
-	if [ $? == 0 ]
-	then
-		echo "Comment added successfully"
-	else
-		echo "error??"
-		exit 1
-	fi
+    if [ $? == 0 ]
+    then
+        echo "Comment added successfully"
+    else
+        echo "error??"
+        exit 1
+    fi
 }
 _ak_modules_comments_usage(){
 	_ak_modules_comments_title
@@ -91,12 +91,12 @@ _ak_modules_comments_usage(){
 }
 
 if [ ! -z $1 ]; then
-	case $1 in
-		help) _ak_modules_comments_usage; exit;;
-		index) _ak_modules_comments_index; exit;;
-		add) _ak_modules_comments_add $2 $3; exit;;
-		create) _ak_modules_comments_create $2; exit;;
-		* ) _ak_modules_comments_usage;;
-	esac
+    case $1 in
+        help) _ak_modules_comments_usage; exit;;
+        index) _ak_modules_comments_index; exit;;
+        add) _ak_modules_comments_add $2 $3; exit;;
+        create) _ak_modules_comments_create $2; exit;;
+        * ) _ak_modules_comments_usage;;
+    esac
 else _ak_modules_comments_usage
 fi
diff --git a/bin/ak-profile b/bin/ak-profile
--- a/bin/ak-profile
+++ b/bin/ak-profile
@@ -11,11 +11,11 @@ logit(){
 # Whatever the command is, we check if $ZPROFILEDIR is there.
 # If NOT we create it and we change dir there.
 if [ ! -d $ZPROFILEDIR ]; then
-	mkdir $ZPROFILEDIR
-	cd $ZPROFILEDIR
-	logit "[INFO]" "zprofiledir created"
+    mkdir $ZPROFILEDIR
+    cd $ZPROFILEDIR
+    logit "INFO" "zprofiledir created"
 else
-	logit "[INFO]" "zprofiledir found"
+    logit "INFO" "zprofiledir found"
 fi
 
 
@@ -25,189 +25,190 @@ fi
 # Hence, we need a specific DATA block that actually has the announcement of a
 # {"key":"value"} pair.
 _ak_modules_profile_show(){
-	if [ ! -z $1 ]
-	then
-		logit "[INFO]" "Working with $1"
+    if [ ! -z $1 ]
+    then
+        logit "INFO" "Working with $1"
         ak-ipfs-cat $(echo $(ak-ipfs-cat $1) | jq '.ipfs' -r)
-	else
-		echo "No DATA provided"
-		exit 1
-	fi
+    else
+        echo "No DATA provided"
+        exit 1
+    fi
 }
 
 # This should retrieve a specific value from our profile otherwise it dumps the
 # whole profile values.
 _ak_modules_profile_propget(){
-	if [ ! -z $1 ]
-	then
-		if [ ! -f $ZPROFILEDIR/$1 ]
-		then
-			echo "property not found"
-		else
-			cat $ZPROFILEDIR/$1
-		fi
-	else
-		echo "No particular property... indexing"
-		_ak_modules_profile_index
-	fi
+    if [ ! -z $1 ]
+    then
+        if [ ! -f $ZPROFILEDIR/$1 ]
+        then
+            echo "property not found"
+        else
+            cat $ZPROFILEDIR/$1
+        fi
+    else
+        echo "No particular property... indexing"
+        _ak_modules_profile_index
+    fi
 }
 
 propwrite(){
-	cat > $ZPROPERTY_FILE << EOF
+    cat > $ZPROPERTY_FILE << EOF
 {
     "$ZPROPERTY_KEY":"${ZPROPERTY_VALUE}"
 }
 EOF
-	if [ $? == 0 ]
-	then
-		echo "Added successfully... proceeding"
-		IPFS_FILE=$(ak-ipfs-add $ZPROPERTY_FILE)
-		echo "Prop writting,,, $IPFS_FILE"
-		_ak_modules_profile_add $ZPROPERTY_KEY
-		cd $ZPROFILEDIR
-	else
-		echo "Couldn't write to file $ZPROFILEDIR/$TO_FILE"
-		exit 1
-	fi
+    if [ $? == 0 ]
+    then
+        echo "Added successfully... proceeding"
+        IPFS_FILE=$(ak-ipfs-add $ZPROPERTY_FILE)
+        echo "Prop writting,,, $IPFS_FILE"
+        _ak_modules_profile_add $ZPROPERTY_KEY
+        cd $ZPROFILEDIR
+    else
+        echo "Couldn't write to file $ZPROFILEDIR/$TO_FILE"
+        exit 1
+    fi
 }
 
 _ak_modules_profile_propset(){
-	if [ ! -z $1 ]
-	then
-		ZPROPERTY_FILE="$ZPROFILEDIR/$1"
-		ZPROPERTY_KEY="$1"
-		if [ ! -f $ZPROPERTY_FILE ]
-		then
-			echo "No such property: $ZPROPERTY_KEY ... creating"
-			ZPROPERTY_VALUE="$2"
-			if [ ! -z "$ZPROPERTY_VALUE" ]
-			then
-				touch $ZPROPERTY_FILE
-				echo "$ZPROPERTY_KEY = $ZPROPERTY_VALUE in file $ZPROPERTY_FILE"
-				propwrite #"$ZPROPERTY_FILE" "${ZPROPERTY_VALUE}"
-			else 
-				echo "No value for $1"
-			fi
-		else
-			echo found $ZPROPERTY_FILE
-			echo "$ZPROPERTY_KEY = $ZPROPERTY_VALUE in file $ZPROPERTY_FILE"
-			ZPROPERTY_VALUE="$2"
-			read -p "Overwrite $1 with ${ZPROPERTY_VALUE} ? " yn
-			case $yn in
-				[Yy]* ) propwrite;;# "$ZPROPERTY_" "${ZPROPERTY_VALUE}";;
-				[Nn]* ) exit 130;;
-				* ) echo "Answer please";;
-			esac
-			echo $IPFS_FILE
-			_ak_modules_profile_show $IPFS_FILE
-		fi
-	else
-		echo "conditions unmet"
-		exit 244
-	fi
+    if [ ! -z $1 ]
+    then
+        ZPROPERTY_FILE="$ZPROFILEDIR/$1"
+        ZPROPERTY_KEY="$1"
+        if [ ! -f $ZPROPERTY_FILE ]
+        then
+            echo "No such property: $ZPROPERTY_KEY ... creating"
+            ZPROPERTY_VALUE="$2"
+            if [ ! -z "$ZPROPERTY_VALUE" ]
+            then
+                touch $ZPROPERTY_FILE
+                echo "$ZPROPERTY_KEY = $ZPROPERTY_VALUE in file $ZPROPERTY_FILE"
+                propwrite #"$ZPROPERTY_FILE" "${ZPROPERTY_VALUE}"
+            else
+                echo "No value for $1"
+            fi
+        else
+            echo found $ZPROPERTY_FILE
+            echo "$ZPROPERTY_KEY = $ZPROPERTY_VALUE in file $ZPROPERTY_FILE"
+            ZPROPERTY_VALUE="$2"
+            read -p "Overwrite $1 with ${ZPROPERTY_VALUE} ? " yn
+            case $yn in
+                [Yy]* ) propwrite;;# "$ZPROPERTY_" "${ZPROPERTY_VALUE}";;
+                [Nn]* ) exit 130;;
+                * ) echo "Answer please";;
+            esac
+            echo $IPFS_FILE
+            _ak_modules_profile_show $IPFS_FILE
+        fi
+    else
+        echo "conditions unmet"
+        exit 244
+    fi
 }
 _ak_modules_profile_index(){
-	FILES="$(ls -1 $ZPROFILEDIR)"
-	i=0
-	echo -n "{"
-	for FILE in $FILES
-	do
-		if [ $FILE != "README" ]; then
-			if [ $i != "0" ]; then
-				echo -n ",";
-			fi
-			PROP=$(echo $(cat $ZPROFILEDIR/$FILE | ak-json2bash) | cut -d '=' -f 1 | awk '{print $0}')
-			VAL=$(echo $(cat $ZPROFILEDIR/$FILE | ak-json2bash) | cut -d '=' -f 2 | awk '{print $1}')
-			echo -n '"'$PROP'":"'$VAL'"';
-			let i+=1
-		fi
-	done
-	echo "}"
+    FILES="$(ls -1 $ZPROFILEDIR)"
+    i=0
+    echo -n "{"
+    for FILE in $FILES
+    do
+        if [ $FILE != "README" ]; then
+            if [ $i != "0" ]; then
+                echo -n ",";
+            fi
+            PROP=$(echo $(cat $ZPROFILEDIR/$FILE | ak-json2bash) | cut -d '=' -f 1 | awk '{print $0}')
+            VAL=$(echo $(cat $ZPROFILEDIR/$FILE | ak-json2bash) | cut -d '=' -f 2 | awk '{print $1}')
+            echo -n '"'$PROP'":"'$VAL'"';
+            let i+=1
+        fi
+    done
+    echo "}"
 }
 _ak_modules_profile_import(){
-	if [ ! -z $1 ]
-	then
-		if [ ! -d $1 ]
-		then
-			echo "Profile folder check: Folder $1 does not exist. Stopping..."
-			exit 4
-		else
-			echo "Profile folder check: Folder $1 exists."
-			fl="$(ls -1 $1)"
-			for f in $fl
-			do
-				_ak_modules_profile_add $1/$f
-			done
-		fi
-	else
-		echo "No value"
-		exit 6
-	fi
-	exit 224
+    if [ ! -z $1 ]
+    then
+        if [ ! -d $1 ]
+        then
+            echo "Profile folder check: Folder $1 does not exist. Stopping..."
+            exit 4
+        else
+            echo "Profile folder check: Folder $1 exists."
+            fl="$(ls -1 $1)"
+            for f in $fl
+            do
+                _ak_modules_profile_add $1/$f
+            done
+        fi
+    else
+        echo "No value"
+        exit 6
+    fi
+    exit 224
 }
 
 # Adds a file as a profile/add ACTION on the zchain.
 _ak_modules_profile_add(){
     TEMP="$(ak-tempassin)"
     cd $TEMP
-	if [ -f $ZPROFILEDIR/$1 ]; then
-		FILE="$ZPROFILEDIR/$1"
-		echo "Adding from " $FILE
-		FILE_IPFS_HASH=$(ak-ipfs-add $FILE)
-		FILE_SIGN_FILE=$(pwd)/$1".asc"
-		gpg2 --homedir $AK_GPGHOME --detach-sign --sign-with $AK_FINGERPRINT --armor --output $FILE_SIGN_FILE $FILE
-		FILE_SIGNATURE=$(ak-ipfs-add $FILE_SIGN_FILE)
-		cat > data <<EOF
+    if [ -f $ZPROFILEDIR/$1 ]; then
+        FILE="$ZPROFILEDIR/$1"
+        echo "Adding from " $FILE
+        FILE_IPFS_HASH=$(ak-ipfs-add $FILE)
+        FILE_SIGN_FILE=$(pwd)/$1".asc"
+        gpg2 --homedir $AK_GPGHOME --detach-sign --sign-with $AK_FINGERPRINT --armor --output $FILE_SIGN_FILE $FILE
+        FILE_SIGNATURE=$(ak-ipfs-add $FILE_SIGN_FILE)
+        cat > data <<EOF
 {
    "datetime":"$(date -u +%s)",
    "ipfs":"$FILE_IPFS_HASH",
    "detach":"$FILE_SIGNATURE"
 }
 EOF
-	else
-		echo "File $FILE doesn't exist";
-		exit 2
-	fi
+    else
+        echo "File $FILE doesn't exist";
+        exit 2
+    fi
 
     ak-zblock-pack "profile/add" $(pwd)/data
-	if [ "$?" -ne 0 ]
-	then
-		echo "error??"
-		exit 1
-	fi
+    if [ "$?" -ne 0 ]
+    then
+        echo "error??"
+        exit 1
+    fi
     echo "Profile added successfully"
     cd $ZPROFILEDIR
     rm -rf "$TEMPASSIN"
 }
 _ak_modules_profile_usage(){
-	echo "Usage:"
-	echo "		$PROGRAM command [options]"
-	echo ""
-	echo "Indexes, shows, imports, adds, sets and gets values from and to the"
+    echo "Usage:"
+    echo "        $PROGRAM command [options]"
+    echo ""
+    echo "Indexes, shows, imports, adds, sets and gets values from and to the"
     echo "zchain and files."
-	echo ""
-	echo -e "\thelp\t\t\t\tPrints this help message"
-	echo -e "\tindex\t\t\t\tShow current status"
-	echo -e "\tshow <data>\t\t\tShow profile entry from specified DATA IPFS CIDv0"
-	echo -e "\tset <property> <value>\t\tSets a profile value"
-	echo -e "\tget <property>\t\t\tGets a profile value from the on-disk file."
-	echo ""
+    echo ""
+    echo "    -h, --help                Prints this help message"
+    echo "    index                     Show current status"
+    echo "    show <data>               Show profile entry from specified DATA IPFS CIDv0"
+    echo "    set <property> <value>    Sets a profile value"
+    echo "    get <property>            Gets a profile value from the on-disk file."
+    echo ""
     echo "Advanced (use with caution may produce duplicate entries):"
-	echo -e "\tadd <file>\t\t\tCreates a data file from the profile file you point to (file should already be in ZPROFILEDIR."
-	echo -e "\timport <folder>\t\t\tImport a folder to zchain #TODO"
-	echo ""
-	exit 0
+    echo "    add <file>                 Creates a data file from the profile file you point"
+    echo "                               to (file should already be in ZPROFILEDIR."
+    echo "    import <folder>            Import a folder to zchain #TODO"
+    echo ""
+    exit 0
 }
 if [ ! -z $1 ]; then
-	case $1 in
-		help) _ak_modules_profile_usage; exit;;
-		index) _ak_modules_profile_index; exit;;
-		show) _ak_modules_profile_show $2; exit;;
-		import) _ak_modules_profile_import $2; exit;;
-		add) _ak_modules_profile_add $2; exit;;
-		set) _ak_modules_profile_propset $2 "$3"; exit;;
-		get) _ak_modules_profile_propget $2; exit;;
-		* ) _ak_modules_profile_usage;;
-	esac
+    case $1 in
+        -h | --help) _ak_modules_profile_usage; exit;;
+        index) _ak_modules_profile_index; exit;;
+        show) _ak_modules_profile_show $2; exit;;
+        import) _ak_modules_profile_import $2; exit;;
+        add) _ak_modules_profile_add $2; exit;;
+        set) _ak_modules_profile_propset $2 "$3"; exit;;
+        get) _ak_modules_profile_propget $2; exit;;
+        * ) _ak_modules_profile_usage;;
+    esac
 else _ak_modules_profile_usage
 fi
diff --git a/bin/ak-sm-files b/bin/ak-sm-files
--- a/bin/ak-sm-files
+++ b/bin/ak-sm-files
@@ -6,28 +6,29 @@ CRD=$(cat .pwd)
 PROGRAM="$(basename $0)"
 #set -xe
 logit(){
-	ak-logthis "<$PROGRAM>" "$1" "$2"
+    ak-logthis "$PROGRAM" "$1" "$2"
 }
 if [ ! -d $ZFILESDIR ]; then
-	mkdir $ZFILESDIR
-	if [ $? == 0 ]
-	then
-		logit "[INFO]" "Folder $ZFILESDIR created!"
-	else
-		logit "[ERROR]" "Failed to create $ZFILESDIR folder"
-		exit 1
-	fi
-	cd $ZFILESDIR
+    mkdir $ZFILESDIR
+    if [ $? == 0 ]
+    then
+        logit "INFO" "Folder $ZFILESDIR created!"
+    else
+        logit "ERROR" "Failed to create $ZFILESDIR folder"
+        exit 1
+    fi
+    cd $ZFILESDIR
 else
-	logit "[INFO]" "$ZFILESDIR found!"
+    logit "INFO" "$ZFILESDIR found!"
 fi
 
 usage(){
-	echo "$PROGRAM - file"
-    echo "  add <file>"
-    echo "  index"
-    echo "  full-index"
-    echo "  ls-map-files"
+    echo "$PROGRAM - file"
+    echo "  -h, --help              Prints this help message"
+    echo "  add <file>              Adds file to zchain as a zblock"
+    echo "  index                   List files"
+    echo "  full-index              List all files"
+    echo "  ls-map-files            List map files"
 }
 
 add(){
@@ -45,59 +46,59 @@ main(){
     echo "Adding $FILENAME"
     logit "[INFO]" "Switching to tmp folder..."
     if [ $? == 0 ]; then
-	    logit "[INFO]" "Success"
+        logit "INFO" "Success"
     else
-	    logit "[ERROR]" "Error with tmp folder"
-	    exit 5
+        logit "ERROR" "Error with tmp folder"
+        exit 5
     fi
     logit "[INFO]" "Copying $1 to $TEMPASSIN"
 
     cp $CRP/$FILENAME $FILENAME
     if [ $? == 0 ]; then
-	    logit "[INFO]" "Copied successfully"
+        logit "INFO" "Copied successfully"
     else
-	    logit "[ERROR]" "Error copying..."
+        logit "ERROR" "Error copying..."
     fi
 
     logit "[INFO]" "Adding $FILENAME to IPFS..."
     FILE_IPFS_HASH=$(ak-ipfs-add $FILENAME)
     if [ $? == 0 ]; then
-	    logit "[INFO]" "Added $FILENAME to IPFS"
+        logit "INFO" "Added $FILENAME to IPFS"
     else
-	    logit "[ERROR]" "Error in adding the $FILENAME to IPFS"
+        logit "ERROR" "Error in adding the $FILENAME to IPFS"
     fi
 
     logit "[INFO]" "Adding $FILE to SHAMAPSYS..."
     FILEMAP_SHA512_HASH=$(ak-sm-filesplitter $FILENAME)
     if [ $? == 0 ]; then
-	    logit "[INFO]" "Added $FILENAME to SHAMAPSYS"
+        logit "INFO" "Added $FILENAME to SHAMAPSYS"
     else
-	    logit "[ERROR]" "Error in adding the $FILENAME to SHAMAPSYS"
+        logit "ERROR" "Error in adding the $FILENAME to SHAMAPSYS"
     fi
 
     logit "[INFO]" "Signing..."
     SIGN_FILE=$FILENAME".asc"
     gpg2 --homedir $AK_GPGHOME --detach-sign --sign-with $AK_FINGERPRINT --armor --output $SIGN_FILE $FILENAME
     if [ $? == 0 ]; then
-	    logit "[INFO]" "Signed"
+        logit "INFO" "Signed"
     else
-	    logit "[ERROR]" "Error while signing"
+        logit "ERROR" "Error while signing"
     fi
 
     logit "[INFO]" "Adding signature to IPFS"
     SIGNATURE=$(ak-ipfs-add $SIGN_FILE)
     if [ $? == 0 ]; then
-	    logit "[INFO]" "Added"
+        logit "INFO" "Added"
     else
-	    logit "[ERROR]" "Error while adding"
+        logit "ERROR" "Error while adding"
     fi
 
     logit "[INFO]" "Adding signature to SHAMAPSYS"
     SHAMAPSIGMAP=$(ak-sm-filesplitter $SIGN_FILE)
     if [ $? == 0 ]; then
-	    logit "[INFO]" "Added"
+        logit "INFO" "Added"
     else
-	    logit "[ERROR]" "Error while adding"
+        logit "ERROR" "Error while adding"
     fi
 
     cat > data <<EOF
@@ -118,10 +119,10 @@ EOF
     ak-zblock-pack sha-files/announce $(pwd)/data
     if [ $? == 0 ]
     then
-	    echo "cool"
+        echo "cool"
     else
-	    echo "not?"
-	    exit 2
+        echo "not?"
+        exit 2
     fi
 }
 
@@ -134,7 +135,7 @@ ls-mapfiles(){
     for f in `find . -type f | sed -e 's/\.\///g'`;do
         FILENAME="$(tail -n1 $f | grep '^[abcdef1234567890]' | awk '{ print $2 }')"
         FILEHASH="$(tail -n1 $f | grep '^[abcdef1234567890]' | awk '{ print $1 }')"
-        MAPFILE="$f" 
+        MAPFILE="$f"
         printf "\nMap: %s\nFilename: %s\nSum: %s\n\n" $MAPFILE $FILENAME $FILEHASH
     done
 }
@@ -150,7 +151,7 @@ if [ ! -z $1 ]; then
         index) index; exit;;
         full-index) full-index; exit;;
         ls-map-files) ls-mapfiles; exit;;
-		*) usage; exit;;
-	esac
+        *) usage; exit;;
+    esac
 else usage
 fi
diff --git a/bin/ak-zchain-chk b/bin/ak-zchain-chk
--- a/bin/ak-zchain-chk
+++ b/bin/ak-zchain-chk
@@ -5,35 +5,35 @@ logit(){
 }
 fix="0"
 usage(){
-	echo "zchain-chk - Check and fix zchain"
-	echo "---------------------------------"
-	echo "Usage:"
-	echo "	--help, -h				Print this help and exit"
-	echo "	--chain <ipns-link>, -n <ipns-link>	Crawl specified chain"
-	echo "	--fix					#TODO Fix your chain"
-	echo ""
-	echo "Note that combined flags don't work for now"
-	echo "Running with no flags crawls your chain"
+    echo "zchain-chk - Check and fix zchain"
+    echo "---------------------------------"
+    echo "Usage:"
+    echo "    --help, -h                             Print this help and exit"
+    echo "    --chain <ipns-link>, -n <ipns-link>    Crawl specified chain"
+    echo "    --fix                                  #TODO Fix your chain"
+    echo ""
+    echo "Note that combined flags don't work for now"
+    echo "Running with no flags crawls your chain"
 }
 
 if [ ! -z "$1" ] && [ "$1" == "-h" ] || [ "$1" == "--help" ]
 then
-	usage
-	exit
+    usage
+    exit
 elif [ ! -z "$1" ] && [ "$1" == "-f" ] || [ "$1" == "--fix" ]
 then
-	fix="1"
-	entrance="$(cat $AK_ZLATEST)"
+    fix="1"
+    entrance="$(cat $AK_ZLATEST)"
 elif [ ! -z "$1" ] && [ "$1" == "-n" ] || [ "$1" == "--chain" ]
 then
-	entrance="$(ak-ipns-resolve $2)"
+    entrance="$(ak-ipns-resolve $2)"
 elif [ ! -z "$1" ]
 then
-	entrance="$1"
+    entrance="$1"
 else
-	# By default we ak-enter from the latest block
-	# We can alter this by changing this value
-	entrance="$(cat $AK_ZLATEST)"
+    # By default we ak-enter from the latest block
+    # We can alter this by changing this value
+    entrance="$(cat $AK_ZLATEST)"
 fi
 
 # We assign the IPFS CIDv0 of an empty file as this is used
@@ -55,92 +55,92 @@ counter=0
 # We break the loop from inside the loop
 while true
 do
-	if [ $counter == 0 ]
-	then
-		echo 'Start checking'
-	fi
-	counter=$(expr $counter + 1)
+    if [ $counter == 0 ]
+    then
+        echo 'Start checking'
+    fi
+    counter=$(expr $counter + 1)
 
-	# Check if $zblock exists as variable
-	if [ ! -v $zblock ]
-	then
-		# Check if it is not our seed cause if it is we skip this part
-		if [ "$zblock" != "$seed" ]
-		then
-			# Reset timestamp since it's introduced later
-			timestamp=''
-			# Announce to stdout which ZBLOCK is being read at the moment
-			ak-logthis "[INFO]" "Examining $zblock"
+    # Check if $zblock exists as variable
+    if [ ! -v $zblock ]
+    then
+        # Check if it is not our seed cause if it is we skip this part
+        if [ "$zblock" != "$seed" ]
+        then
+            # Reset timestamp since it's introduced later
+            timestamp=''
+            # Announce to stdout which ZBLOCK is being read at the moment
+            logit "INFO" "Examining $zblock"
 
-			# We create files named after each ZBLOCK IPFS CID for later
-			# reference. Files are empty.
-			touch $AK_ZBLOCKDIR/$zblock
-			ak-logthis "[INFO]" "Created reference"
+            # We create files named after each ZBLOCK IPFS CID for later
+            # reference. Files are empty.
+            touch $AK_ZBLOCKDIR/$zblock
+            logit "INFO" "Created reference"
 
-			# We concatenate the zblock's contents, pipe them through filter
-			# ak-json2bash and output them to tmp-file
-			ak-ipfs-cat $zblock | ak-json2bash > tmp-zblock
-			ak-logthis "[INFO]" "ZBLOCK $zblock READ"
+            # We concatenate the zblock's contents, pipe them through filter
+            # ak-json2bash and output them to tmp-file
+            ak-ipfs-cat $zblock | ak-json2bash > tmp-zblock
+            logit "INFO" "ZBLOCK $zblock READ"
 
-			# Supposingly you are on a safe environment and you only have
-			# access to your chain, I would consider mild secure to source
-			# the files into your bash.
-			# File an issue/pull request if you think it can be done better!!
-			source tmp-zblock
-			ak-logthis "[INFO]" "ZBLOCK SOURCED"
+            # Supposingly you are on a safe environment and you only have
+            # access to your chain, I would consider mild secure to source
+            # the files into your bash.
+            # File an issue/pull request if you think it can be done better!!
+            source tmp-zblock
+            logit "INFO" "ZBLOCK SOURCED"
 
-			# Same as above applies to BLOCK and DATA subparts of each ZBLOCK
-			# BLOCKS
-			ak-ipfs-cat $block | ak-json2bash > tmp-block
-			source tmp-block
-			ak-logthis "[INFO]" "BLOCK $block SOURCED"
-			touch $AK_BLOCKDIR/$block
-			ak-logthis "[INFO]" "BLOCK REFERENCED"
-			module="$(echo $action | sed -e 's/\// /g' | awk '{ print $1 }')"
-			ak-logthis "[INFO]" "DATA is $module module."
-			command="$(echo $action | sed -e 's/\// /g' | awk '{ print $2 }')"
-			ak-logthis "[INFO]" "COMMAND is $command"
-			if [ ! -v $timestamp ]
-			then
-				echo "$timestamp : $zblock -> $block -> $previous"
-				blocks_found[$counter]="$block"
-			fi
-			touch $AK_DATADIR/$data
+            # Same as above applies to BLOCK and DATA subparts of each ZBLOCK
+            # BLOCKS
+            ak-ipfs-cat $block | ak-json2bash > tmp-block
+            source tmp-block
+            logit "INFO" "BLOCK $block SOURCED"
+            touch $AK_BLOCKDIR/$block
+            logit "INFO" "BLOCK REFERENCED"
+            module="$(echo $action | sed -e 's/\// /g' | awk '{ print $1 }')"
+            logit "INFO" "DATA is $module module."
+            command="$(echo $action | sed -e 's/\// /g' | awk '{ print $2 }')"
+            logit "INFO" "COMMAND is $command"
+            if [ ! -v $timestamp ]
+            then
+                echo "$timestamp : $zblock -> $block -> $previous"
+                blocks_found[$counter]="$block"
+            fi
+            touch $AK_DATADIR/$data
 
-			# Now, since we sourced the BLOCK to our terminal, we can search
-			# for $previous variable. In case we don't find one, we exit with
-			# code 0
-			if [ -v $previous ]
-			then
-				ak-logthis "[ERROR]" "Block $block has no previous zblock"
-				echo "Chain with no genesis"
-				if [ "$fix" == "1" ]
-				then
-					echo "LOL"
-				else
-					echo "Blocks found and need repacking..."
-					for value in ${blocks_found[@]}
-					do
-						echo $value
-						ak-ipfs-cat $value | jq -M
-					done
-				fi
-				exit 0
-			# Otherwise, we inform of the sequence
-			else
-				zblock=$previous
-			fi
-		# Now check if it is equal to the seed
-		# which apparently means we reached the seed.
-		elif [ "$zblock" == "$seed" ]
-		then
-			echo "Chain is OK with GENESIS block = $seed"
-			ak-logthis "[INFO]" "Counter $counter"
-			exit 0
-		fi
-	# And finally, if nothing is there exit with error
-	else 
-		ak-logthis "[ERROR]" "Check not passed... No previous IPFS CID"
-		exit 1
-	fi
+            # Now, since we sourced the BLOCK to our terminal, we can search
+            # for $previous variable. In case we don't find one, we exit with
+            # code 0
+            if [ -v $previous ]
+            then
+                logit "ERROR" "Block $block has no previous zblock"
+                echo "Chain with no genesis"
+                if [ "$fix" == "1" ]
+                then
+                    echo "LOL"
+                else
+                    echo "Blocks found and need repacking..."
+                    for value in ${blocks_found[@]}
+                    do
+                        echo $value
+                        ak-ipfs-cat $value | jq -M
+                    done
+                fi
+                exit 0
+            # Otherwise, we inform of the sequence
+            else
+                zblock=$previous
+            fi
+        # Now check if it is equal to the seed
+        # which apparently means we reached the seed.
+        elif [ "$zblock" == "$seed" ]
+        then
+            echo "Chain is OK with GENESIS block = $seed"
+            logit "INFO" "Counter $counter"
+            exit 0
+        fi
+    # And finally, if nothing is there exit with error
+    else
+        logit "ERROR" "Check not passed... No previous IPFS CID"
+        exit 1
+    fi
 done
