Deployed space lazers to eliminate tabbed spaces
- Also: _ak_not_implemented introduced

diff --git a/bin/ak-data-expand b/bin/ak-data-expand
--- a/bin/ak-data-expand
+++ b/bin/ak-data-expand
@@ -11,94 +11,94 @@ fi
 
 if [ ! -z "$1" ] && [ ! -z "$2" ]
 then
-	echo -n "$1" | grep -e 'Qm.\{44\}' >/dev/null
-	if [ "$?" -ne 0 ]
-	then
-		logit "ERROR" "Invalid hash format for $1"
-		exit 1
-	fi
-	_ak_ipfs_cat $1 > /dev/null
-	if [ "$?" -ne 0 ]
-	then
-		logit "ERROR" "Error while reading $1"
-		exit 1
-	fi
-	_ak_ipfs_cat $1 | jq -M > /dev/null
-	if [ "$?" -ne 0 ]
-	then
-		logit "ERROR" "Error while parsing JSON for $1"
-		exit 1
-	fi
-	_ak_ipfs_cat $1 | jq | grep ipfs > /dev/null
-	if [ "$?" -ne 0 ]
-	then
-		logit "ERROR" "Error while extracting data from JSON for $1"
-		exit 1
-	fi
-	DATA="$(_ak_ipfs_cat $1 | jq | grep ipfs | sed -e 's/"ipfs": "//g; s/[",]//g; s/ //g')"
-	if [ "$?" -ne 0 ]
-	then
-		logit "ERROR" "Error while extracting data from JSON for $1"
-		exit 1
-	fi
-	_ak_ipfs_cat $1 | jq | grep detach > /dev/null
-	if [ "$?" -ne 0 ]
-	then
-		logit "ERROR" "Error while extracting data from JSON for $1"
-		exit 1
-	fi
-	DETACH="$(_ak_ipfs_cat $1 | jq | grep detach | sed -e 's/"detach": "//g; s/[",]//g; s/ //g')"
-	if [ "$?" -ne 0 ]
-	then
-		logit "ERROR" "Error while extracting data from JSON for $1"
-		exit 1
-	fi
-	echo -n "$2" | grep -e 'Qm.\{44\}' >/dev/null
-	if [ "$?" -ne 0 ]
-	then
-	    logit "ERROR" "Invalid hash format for $2"
-	    exit 1
-	fi
+    echo -n "$1" | grep -e 'Qm.\{44\}' >/dev/null
+    if [ "$?" -ne 0 ]
+    then
+        logit "ERROR" "Invalid hash format for $1"
+        exit 1
+    fi
+    _ak_ipfs_cat $1 > /dev/null
+    if [ "$?" -ne 0 ]
+    then
+        logit "ERROR" "Error while reading $1"
+        exit 1
+    fi
+    _ak_ipfs_cat $1 | jq -M > /dev/null
+    if [ "$?" -ne 0 ]
+    then
+        logit "ERROR" "Error while parsing JSON for $1"
+        exit 1
+    fi
+    _ak_ipfs_cat $1 | jq | grep ipfs > /dev/null
+    if [ "$?" -ne 0 ]
+    then
+        logit "ERROR" "Error while extracting data from JSON for $1"
+        exit 1
+    fi
+    DATA="$(_ak_ipfs_cat $1 | jq | grep ipfs | sed -e 's/"ipfs": "//g; s/[",]//g; s/ //g')"
+    if [ "$?" -ne 0 ]
+    then
+        logit "ERROR" "Error while extracting data from JSON for $1"
+        exit 1
+    fi
+    _ak_ipfs_cat $1 | jq | grep detach > /dev/null
+    if [ "$?" -ne 0 ]
+    then
+        logit "ERROR" "Error while extracting data from JSON for $1"
+        exit 1
+    fi
+    DETACH="$(_ak_ipfs_cat $1 | jq | grep detach | sed -e 's/"detach": "//g; s/[",]//g; s/ //g')"
+    if [ "$?" -ne 0 ]
+    then
+        logit "ERROR" "Error while extracting data from JSON for $1"
+        exit 1
+    fi
+    echo -n "$2" | grep -e 'Qm.\{44\}' >/dev/null
+    if [ "$?" -ne 0 ]
+    then
+        logit "ERROR" "Invalid hash format for $2"
+        exit 1
+    fi
     gpg="$2"
     _ak_ipfs_get $gpg > /dev/null 2>&1
     if [ "$?" -ne 0 ]
     then
-	logit "ERROR" "Could not get GPG key: $gpg"
-	exit 1
+    logit "ERROR" "Could not get GPG key: $gpg"
+    exit 1
     fi
     _ak_gpg_key_import_from_file $gpg > /dev/null 2>&1
     if [ "$?" -ne 0 ]
     then
-		logit "ERROR" "Could not import GPG key: $gpg"
-		exit 1
-	fi
-	_ak_ipfs_get $DETACH > /dev/null 2>&1
-	if [ "$?" -ne 0 ]
-	then
-		logit "ERROR" "Error while getting signature: $DETACH for data: $DATA"
-		exit 1
-	fi
-	mv $DETACH $DATA.asc
-	logit "INFO" "Block signature downloaded"
-	_ak_ipfs_get $DATA > /dev/null 2>&1
-	if [ "$?" -ne 0 ]
-	then
-		logit "ERROR" "Error while getting data: $DATA"
-		exit 1
-	fi
-	logit "INFO" "Data downloaded: $DATA"
-	_ak_gpg_verify_signature $DATA.asc $DATA > /dev/null 2>&1
-	if [ "$?" -ne 0 ]
-	then
-		logit "ERROR" "Error while verifying signature for $DATA"
-		exit 1
-	fi
+        logit "ERROR" "Could not import GPG key: $gpg"
+        exit 1
+    fi
+    _ak_ipfs_get $DETACH > /dev/null 2>&1
+    if [ "$?" -ne 0 ]
+    then
+        logit "ERROR" "Error while getting signature: $DETACH for data: $DATA"
+        exit 1
+    fi
+    mv $DETACH $DATA.asc
+    logit "INFO" "Block signature downloaded"
+    _ak_ipfs_get $DATA > /dev/null 2>&1
+    if [ "$?" -ne 0 ]
+    then
+        logit "ERROR" "Error while getting data: $DATA"
+        exit 1
+    fi
+    logit "INFO" "Data downloaded: $DATA"
+    _ak_gpg_verify_signature $DATA.asc $DATA > /dev/null 2>&1
+    if [ "$?" -ne 0 ]
+    then
+        logit "ERROR" "Error while verifying signature for $DATA"
+        exit 1
+    fi
     mv $DATA $AK_WORKDIR/ipfs
-	logit "INFO" "Block signature verified"
+    logit "INFO" "Block signature verified"
     echo -n '"data":"'$1'","'$1'":'$(_ak_ipfs_cat $1|jq -M -c)','
-	exit 0
+    exit 0
 else
-	echo "Usage: $PROGRAM HASH GPG"
-	exit 1
+    echo "Usage: $PROGRAM HASH GPG"
+    exit 1
 fi
 
diff --git a/bin/ak-find-latest-mined-sblock b/bin/ak-find-latest-mined-sblock
--- a/bin/ak-find-latest-mined-sblock
+++ b/bin/ak-find-latest-mined-sblock
@@ -15,63 +15,63 @@ then
 fi
 
 further(){
-	# logit "INFO" "Diving into $1"
-	lookfor $1
+    # logit "INFO" "Diving into $1"
+    lookfor $1
 }
 
 lookfor(){
-	echo -n $1 | grep -e '[0-9a-f]\{128\}' > /dev/null
-	if [ ! $? = 0 ]
-	then
-		logit "ERROR" "Oops!!! The argument passed, does not match the regular expression!"
-	else
-		counters[$CHAIN_PARENT]="$(expr ${counters[$CHAIN_PARENT]} + 1)"
-		if [ ! $? = 0 ]
-		then
-			echo "$1, $counters[$1]"
-			exit 1
-		fi
-		logit "INFO" "Accessing file: $1"
-	#	echo "$1 file:"
-	#	cat "$1" | jq
-		NEXT_TARGET="$(cat "$1" | jq | grep previous | tr -d ' ' | sed -e 's/previous//g; s/[",:]//g;')"
-		if [ ! "$NEXT_TARGET" = "" ]
-		then
-			logit "INFO" "Found previous: $NEXT_TARGET"
-			if [ ! -f "$NEXT_TARGET" ]
-			then
-				logit "WARNING" "Could not find $NEXT_TARGET"
-			else
-				further "$NEXT_TARGET"
-			fi
-		else
-			logit "WARNING" "No next target found. So long for $1"
-		fi
-	fi
+    echo -n $1 | grep -e '[0-9a-f]\{128\}' > /dev/null
+    if [ ! $? = 0 ]
+    then
+        logit "ERROR" "Oops!!! The argument passed, does not match the regular expression!"
+    else
+        counters[$CHAIN_PARENT]="$(expr ${counters[$CHAIN_PARENT]} + 1)"
+        if [ ! $? = 0 ]
+        then
+            echo "$1, $counters[$1]"
+            exit 1
+        fi
+        logit "INFO" "Accessing file: $1"
+    #    echo "$1 file:"
+    #    cat "$1" | jq
+        NEXT_TARGET="$(cat "$1" | jq | grep previous | tr -d ' ' | sed -e 's/previous//g; s/[",:]//g;')"
+        if [ ! "$NEXT_TARGET" = "" ]
+        then
+            logit "INFO" "Found previous: $NEXT_TARGET"
+            if [ ! -f "$NEXT_TARGET" ]
+            then
+                logit "WARNING" "Could not find $NEXT_TARGET"
+            else
+                further "$NEXT_TARGET"
+            fi
+        else
+            logit "WARNING" "No next target found. So long for $1"
+        fi
+    fi
 }
 
 templistblock="$(mktemp)"
 find . -type f | sed 's/^\.\/000/000/g' | grep '^000'  | sort > $templistblock
 while IFS="" read -r p || [ -n "$p" ]
 do
-#	if [ ! "$p" = "" ] && [ ! "$p" = "tmplistblock" ]
-	if [ "$(echo $p | tr -d '\n' | wc -c)" = 128 ]
-	then
+#    if [ ! "$p" = "" ] && [ ! "$p" = "tmplistblock" ]
+    if [ "$(echo $p | tr -d '\n' | wc -c)" = 128 ]
+    then
         filename="$(basename $p)"
-		logit "INFO" "Investigating $filename..."
-		export CHAIN_PARENT="$filename"
-		counters[$CHAIN_PARENT]=1
-		lookfor "$filename"
-	else
-		logit "WARNING" "Nothing to do with $filename"
-	fi
+        logit "INFO" "Investigating $filename..."
+        export CHAIN_PARENT="$filename"
+        counters[$CHAIN_PARENT]=1
+        lookfor "$filename"
+    else
+        logit "WARNING" "Nothing to do with $filename"
+    fi
 done < $templistblock
 rm $templistblock
 max=0
 max_holder=0
 for value in "${!counters[@]}"
 do
-    #	echo "${value} : ${counters[${value}]}"
+    #    echo "${value} : ${counters[${value}]}"
     if [ ${counters[${value}]} -gt $max  ]
     then
         max="${counters[${value}]}"
diff --git a/bin/ak-fs-add b/bin/ak-fs-add
--- a/bin/ak-fs-add
+++ b/bin/ak-fs-add
@@ -24,12 +24,20 @@
 # Uncomment next line if you want to debug
 # set -xe
 PROGRAM="$(basename $0)"
+source $AK_LIBDIR/_ak_fs
+source $AK_LIBDIR/_ak_log
 
 if [ ! -f "$1" ]
 then
-    echo "ERROR File not found"
+    logit "ERROR" "File $1 not found"
     exit 1
 else
+    # TODO
+    # Side hustle, save the original hash and original filename
+    # This won't be expected in general
+    # The idea is:
+    # sha256sum as quick pointer to root of the tree
+    #
     base64 $1 > file
     FILE="file"
 fi
@@ -57,12 +65,11 @@ rm -rf $TEMPORARYDIR
 if [ ! -d "$TECHDIR" ]
 then
     mkdir -p "$TECHDIR"
-    if [ "$?" == 0 ]
+    if [ $? == 0 ]
     then
         logit "INFO" "Folder $TECHDIR created!"
     else
         logit "ERROR" "Problem occured while creating $TECHDIR"
-        echo "ERROR Can't create $TECHDIR"
         exit 1
     fi
 else
@@ -73,12 +80,11 @@ fi
 if [ ! -d "$FILEMAPSDIR" ]
 then
     mkdir -p "$FILEMAPSDIR"
-    if [ "$?" == 0 ]
+    if [ $? == 0 ]
     then
         logit "INFO" "Folder $FILEMAPSDIR created!"
     else
         logit "ERROR" "Problem occured while creating $FILEMAPSDIR"
-        echo "ERROR Can't create $FILEMAPSDIR"
         exit 1
     fi
 else
@@ -89,12 +95,11 @@ fi
 if [ ! -d "$CHKDIR" ]
 then
     mkdir -p "$CHKDIR"
-    if [ "$?" == 0 ]
+    if [ $? == 0 ]
     then
         logit "INFO" "Folder $CHKDIR created!"
     else
         logit "ERROR" "Problem occured while creating $CHKDIR"
-        echo "ERROR Can't create $CHKDIR"
         exit 1
     fi
 else
@@ -105,7 +110,7 @@ fi
 if [ ! -d "$MERKLEDIR" ]
 then
     mkdir -p "$MERKLEDIR"
-    if [ "$?" == 0 ]
+    if [ $? == 0 ]
     then
         logit "INFO" "Folder $MERKLEDIR created!"
     else
diff --git a/bin/ak-sm-filejoiner b/bin/ak-sm-filejoiner
--- a/bin/ak-sm-filejoiner
+++ b/bin/ak-sm-filejoiner
@@ -5,11 +5,11 @@ set -xe
 PROGRAM="$(basename $0)"
 
 usage(){
-	echo "$PROGRAM <hash>"
+    echo "$PROGRAM <hash>"
 }
 
 cdaw(){
-	pwd > tmp_holder
+    pwd > tmp_holder
 }
 
 cdaw
@@ -20,12 +20,12 @@ TMPWD="/tmp/rjs"
 
 if [ ! -d "$TMPWD" ]
 then
-	mkdir -p "$TMPWD"
-	if [ "$?" != 0 ]
-	then
-		echo "Can't create $TMPWD dir"
-		exit 1
-	fi
+    mkdir -p "$TMPWD"
+    if [ "$?" != 0 ]
+    then
+        echo "Can't create $TMPWD dir"
+        exit 1
+    fi
 fi
 
 MAPSDIR="$AK_WORKDIR/fmp"
@@ -35,54 +35,54 @@ CHKDIR="$AK_WORKDIR/ftr"
 cd $CHKDIR
 if [ "$?" != 0 ]
 then
-	echo "Can't get dir"
-	exit 1
+    echo "Can't get dir"
+    exit 1
 fi
 
 if [ ! -z $1 ]
 then
-	MAPSFILE="$1"
+    MAPSFILE="$1"
 
-	echo '#!/bin/bash' > script
-	
+    echo '#!/bin/bash' > script
+
     # We create a script to copy all the chunks and rename them to their serialized
     # name produced by split when we splitted the file
-	awk '{print "cp '$CHKDIR'/"$1" '$TMPWD'/"$2" "}' $MAPSDIR/$MAPSFILE| grep chk >> script
+    awk '{print "cp '$CHKDIR'/"$1" '$TMPWD'/"$2" "}' $MAPSDIR/$MAPSFILE| grep chk >> script
 
-	bash script
+    bash script
 
-	if [ "$?" != 0 ]
-	then
-		echo "Error executing copy script"
-		exit 1
-	fi
-	rm script
+    if [ "$?" != 0 ]
+    then
+        echo "Error executing copy script"
+        exit 1
+    fi
+    rm script
 
-	cd $TMPWD
+    cd $TMPWD
 
-	echo "$PWD"
+    echo "$PWD"
 
     # Final name we are going to rename to
-	OUTPUT="$(tail -n1 $MAPSDIR/$MAPSFILE | awk '{print $2}')"
+    OUTPUT="$(tail -n1 $MAPSDIR/$MAPSFILE | awk '{print $2}')"
 
-	echo $OUTPUT
+    echo $OUTPUT
 
     # We grep the MAPSFILE for chk filenames in lines and we print them all in
     # one line so the first `cat` will concatenate all chunks to OUTPUT
-	cat $(echo -n $(cat $MAPSDIR/$MAPSFILE|grep chk|awk '{print $2" "}'|tr -d '\n')) > $OUTPUT
+    cat $(echo -n $(cat $MAPSDIR/$MAPSFILE|grep chk|awk '{print $2" "}'|tr -d '\n')) > $OUTPUT
 
     # We check if everything is okay
-	sha512sum -c $MAPSDIR/$MAPSFILE
+    sha512sum -c $MAPSDIR/$MAPSFILE
     if [ "$?" != "0" ]; then
         logit "ERROR" "Error while checking sums"
         exit 1
     fi
-	
-	mv $OUTPUT $CURDIR
 
-	rm -rf "$TMPWD"
+    mv $OUTPUT $CURDIR
 
-	rm $CURDIR/tmp_holder
+    rm -rf "$TMPWD"
+
+    rm $CURDIR/tmp_holder
 else
-	usage
+    usage
 fi
diff --git a/bin/ak-sm-filesplitter b/bin/ak-sm-filesplitter
--- a/bin/ak-sm-filesplitter
+++ b/bin/ak-sm-filesplitter
@@ -23,10 +23,10 @@ PROGRAM="$(basename $0)"
 
 if [ ! -f "$1" ]
 then
-	echo "ERROR File not found"
-	exit 1
+    echo "ERROR File not found"
+    exit 1
 else
-	FILE="$1"
+    FILE="$1"
 fi
 
 # The directory where the chunked data will be living at
@@ -48,49 +48,49 @@ source $AK_LIBDIR/_ak_log
 # TECHDIR
 if [ ! -d "$TECHDIR" ]
 then
-	mkdir -p "$TECHDIR"
-	if [ "$?" == 0 ]
-	then
-		logit "INFO" "Folder $TECHDIR created!"
-	else
-		logit "ERROR" "Problem occured while creating $TECHDIR"
-		echo "ERROR Can't create $TECHDIR"
-		exit 1
-	fi
+    mkdir -p "$TECHDIR"
+    if [ "$?" == 0 ]
+    then
+        logit "INFO" "Folder $TECHDIR created!"
+    else
+        logit "ERROR" "Problem occured while creating $TECHDIR"
+        echo "ERROR Can't create $TECHDIR"
+        exit 1
+    fi
 else
-	logit "INFO" "Temp dir found"
+    logit "INFO" "Temp dir found"
 fi
 
 # FILEMAPSDIR
 if [ ! -d "$FILEMAPSDIR" ]
 then
-	mkdir -p "$FILEMAPSDIR"
-	if [ "$?" == 0 ]
-	then
-		logit "INFO" "Folder $FILEMAPSDIR created!"
-	else
-		logit "ERROR" "Problem occured while creating $FILEMAPSDIR"
-		echo "ERROR Can't create $FILEMAPSDIR"
-		exit 1
-	fi
+    mkdir -p "$FILEMAPSDIR"
+    if [ "$?" == 0 ]
+    then
+        logit "INFO" "Folder $FILEMAPSDIR created!"
+    else
+        logit "ERROR" "Problem occured while creating $FILEMAPSDIR"
+        echo "ERROR Can't create $FILEMAPSDIR"
+        exit 1
+    fi
 else
-	logit "INFO" "Mapsdir found"
+    logit "INFO" "Mapsdir found"
 fi
 
 # CHKDIR
 if [ ! -d "$CHKDIR" ]
 then
-	mkdir -p "$CHKDIR"
-	if [ "$?" == 0 ]
-	then
-		logit "INFO" "Folder $CHKDIR created!"
-	else
-		logit "ERROR" "Problem occured while creating $CHKDIR"
-		echo "ERROR Can't create $CHKDIR"
-		exit 1
-	fi
+    mkdir -p "$CHKDIR"
+    if [ "$?" == 0 ]
+    then
+        logit "INFO" "Folder $CHKDIR created!"
+    else
+        logit "ERROR" "Problem occured while creating $CHKDIR"
+        echo "ERROR Can't create $CHKDIR"
+        exit 1
+    fi
 else
-	logit "INFO" "Workdir found"
+    logit "INFO" "Workdir found"
 fi
 
 # Uncomment next line in case you want to debug the resulting script as well
@@ -109,7 +109,7 @@ cd $TECHDIR
 # move them to CHKDIR
 sha512sum  * > $TEMPORARYDIR/map; while IFS="" read -r p || [ -n "$p" ]
 do
-	echo $p | awk '{print "mv " $2 " '$CHKDIR'" $1}' >> $TEMPORARYDIR/cmd_queue.sh
+    echo $p | awk '{print "mv " $2 " '$CHKDIR'" $1}' >> $TEMPORARYDIR/cmd_queue.sh
 done < $TEMPORARYDIR/map
 
 # We run the crafted script
