Added checks to detect success and failure of underlying commands being run

diff --git a/bin/ak-ipfs-block-stat b/bin/ak-ipfs-block-stat
--- a/bin/ak-ipfs-block-stat
+++ b/bin/ak-ipfs-block-stat
@@ -1,3 +1,8 @@
 #!/bin/bash
+PROGRAM="$(basename $0)"
 ipfs block stat "$1"
-
+if [ "$?" != "0" ]
+then
+    ak-logthis "<$PROGRAM>" "[ERROR]" "Failed to retrieve stat of block $1"
+    exit 1
+fi
diff --git a/bin/ak-ipfs-files-cp b/bin/ak-ipfs-files-cp
--- a/bin/ak-ipfs-files-cp
+++ b/bin/ak-ipfs-files-cp
@@ -1,3 +1,8 @@
 #!/bin/bash
+PROGRAM="$(basename $0)"
 ipfs files cp "$1" "$2"
-
+if [ "$?" != "0" ]
+then
+    ak-logthis "<$PROGRAM>" "[ERROR]" "Failed to copy $1 to $2"
+    exit 1
+fi
diff --git a/bin/ak-ipfs-files-stat b/bin/ak-ipfs-files-stat
--- a/bin/ak-ipfs-files-stat
+++ b/bin/ak-ipfs-files-stat
@@ -1,3 +1,8 @@
 #!/bin/bash
+PROGRAM="$(basename $0)"
 ipfs files stat "$1"
-
+if [ "$?" != "0" ]
+then
+    ak-logthis "<$PROGRAM>" "[ERROR]" "Failed to get file's stats $1"
+    exit 1
+fi
diff --git a/bin/ak-ipfs-key-list b/bin/ak-ipfs-key-list
--- a/bin/ak-ipfs-key-list
+++ b/bin/ak-ipfs-key-list
@@ -1,2 +1,8 @@
 #!/bin/bash
+PROGRAM="$(basename $0)"
 ipfs key list
+if [ "$?" != "0" ]
+then
+    ak-logthis "<$PROGRAM>" "[ERROR]" "Failed to get key list"
+    exit 1
+fi
diff --git a/bin/ak-ipfs-name-resolve b/bin/ak-ipfs-name-resolve
--- a/bin/ak-ipfs-name-resolve
+++ b/bin/ak-ipfs-name-resolve
@@ -1,3 +1,9 @@
 #!/bin/bash
+PROGRAM="$(basename $0)"
 ipfs name resolve "$1"
+if [ "$?" != "0" ]
+then
+    ak-logthis "<$PROGRAM>" "[ERROR]" "Failed to resolve $1"
+    exit 1
+fi
 
diff --git a/bin/ak-ipfs-starter b/bin/ak-ipfs-starter
--- a/bin/ak-ipfs-starter
+++ b/bin/ak-ipfs-starter
@@ -1,2 +1,8 @@
 #!/bin/bash
+PROGRAM="$(basename $0)"
 screen -dmS ipfs-daemon ipfs daemon
+if [ "$?" != "0" ]
+then
+    ak-logthis "<$PROGRAM>" "[ERROR]" "Failed to start IPFS daemon"
+    exit 1
+fi
