Renaming to prefix convention, introduced ipfs wrappers so it can be easier to maintain, changes in filesplitter and filejoiner as they move sm submodule namespace... like there are namespaces in bash or something

diff --git a/bin/ak-news b/bin/ak-news
--- a/bin/ak-news
+++ b/bin/ak-news
@@ -1,19 +1,27 @@
 #!/bin/bash
+PROGRAM=$(basename $0)
+
 ZNEWSDIR="$AK_WORKDIR/news"
 TEMP="/tmp/aktmp"
-echo $ZNEWSDIR
+
+logit(){
+    ak-logthis "<$PROGRAM>" "$1" "$2"
+}
+
 if [ ! -d $ZNEWSDIR ]; then
 	mkdir $ZNEWSDIR
-	cd $ZNEWSDIR
-	git init
-	echo "News repository" > README
-	echo "Qmetc" >> README
-	git add README
-	git commit -m "Initiated news repository"
-	echo "znewsdir created along with git repo"
+    if [ "$?" == 0 ]; then
+        logit "[INFO]" "$ZNEWSDIR created"
+    else
+	    logit "[ERROR]" "$ZNEWSDIR couldn't be created"
+        exit 1
+    fi
 else
-	echo "znewsdir found"
+	logit "[INFO]" "$ZNEWSDIR found"
 fi
+
+cd $ZNEWSDIR
+
 tempassin(){
 	if [ ! -z $1 ]
 	then
@@ -27,6 +35,7 @@ tempassin(){
 	fi
 	cd $TEMPASSIN
 }
+
 create(){
 	tempassin $TEMP
 	curpath="$(pwd)"
@@ -35,15 +44,12 @@ create(){
 	echo "Renaming..."
 	TITLE="$(head -n 1 $NEWS_FILE)"
 	TO_FILE=$NEWS_FILE-$(echo $TITLE | tr '[:upper:]' '[:lower:]' | sed -e 's/ /\_/g' )
-	IPFS_FILE=$(ipfs add -q $NEWS_FILE)
+	IPFS_FILE=$(ak-ipfs-add $NEWS_FILE)
 	mv $NEWS_FILE $ZNEWSDIR/$TO_FILE
 	sed -e 's,Qm.*,'"$IPFS_FILE"',g' $ZNEWSDIR/README
 	add $TO_FILE
 	echo "Adding to git repo..."
 	cd $ZNEWSDIR
-	git add $TO_FILE README
-	git commit -m "Added $TO_FILE with $(head -n 1 $ZNEWSDIR/$TO_FILE)"
-	git clean --force
 	# rm -rf $TEMP 
 }
 index(){
@@ -53,13 +59,13 @@ index(){
 	do
 		DATE=$(echo $FILE | cut -d - -f 1 | awk '{print $1}')
 		TITLE=$(head -n 1 $ZNEWSDIR/$FILE)
-		echo $i \| $DATE \| $TITLE
+        IPFS_HASH=$(ak-ipfs-addn $ZNEWSDIR/$FILE)
+		echo $i \| $IPFS_HASH \| $DATE \| $TITLE
 		let i+=1
 	done	
 }
 title(){
-	echo	ak-news-cli
-	echo "--------------"
+    echo $PROGRAM
 }
 import(){
 	echo "#TODO"
@@ -93,10 +99,10 @@ add2(){
 		echo "Adding news from " $FILE
 		DATETIME=$(echo $FILE | cut -d - -f 1 | awk '{print $1}')
 		TITLE=$(head -n 1 $FILE)
-		FILE_IPFS_HASH=$(ipfs add -q $FILE)
+		FILE_IPFS_HASH=$(ak-ipfs-add $FILE)
 		FILE_SIGN_FILE=$FILE".asc"
 		gpg --detach-sign --sign-with $FINGERPRINT --armor --output $FILE_SIGN_FILE $FILE
-		FILE_SIGNATURE=$(ipfs add -q $FILE_SIGN_FILE)
+		FILE_SIGNATURE=$(ak-ipfs-add $FILE_SIGN_FILE)
 		cat > data <<EOF
 {
    "datetime":"$DATETIME",
@@ -110,7 +116,7 @@ EOF
 		echo "File $FILE doesn't exist";
 		exit 2
 	fi
-	pack_z_block "news/add" data
+	ak-pack_z_block "news/add" data
 	if [ $? == 0 ]
 	then
 		echo "News added successfully"
@@ -126,10 +132,10 @@ add(){
 		echo "Adding news from " $FILE
 		DATETIME=$(echo $FILE | cut -d - -f 1 | awk '{print $1}')
 		TITLE=$(head -n 1 $ZNEWSDIR/$FILE)
-		FILE_IPFS_HASH=$(ipfs add -q $ZNEWSDIR/$FILE)
+		FILE_IPFS_HASH=$(ak-ipfs-add $ZNEWSDIR/$FILE)
 		FILE_SIGN_FILE=$FILE".asc"
 		gpg --detach-sign --sign-with $FINGERPRINT --armor --output $FILE_SIGN_FILE $ZNEWSDIR/$FILE
-		FILE_SIGNATURE=$(ipfs add -q $FILE_SIGN_FILE)
+		FILE_SIGNATURE=$(ak-ipfs-add $FILE_SIGN_FILE)
 		cat > data <<EOF
 {
    "datetime":"$DATETIME",
@@ -143,7 +149,7 @@ EOF
 		echo "File $FILE doesn't exist";
 		exit 2
 	fi
-	pack_z_block "news/add" data
+	ak-pack_z_block "news/add" data
 	if [ $? == 0 ]
 	then
 		echo "News added successfully"
@@ -156,7 +162,7 @@ usage(){
 	echo "#TODO"
 	echo "All you need to know is that there are two options available:"
 	echo "help		Prints this help message"
-	echo "index		Prints an indexed table of your news files"
+	echo "local-index		Prints an indexed table of your news files"
 	echo "import <file>	#TODO"
 	echo "add <file>	Creates a data file from the news file you point to"
 	echo "create		Vim is going to pop up, you will write and save your"
@@ -167,7 +173,7 @@ title
 if [ ! -z $1 ]; then
 	case $1 in
 		help) usage; exit;;
-		index) index; exit;;
+		local-index) index; exit;;
 		import) import $2; exit;;
 		add) add2 $2; exit;;
 		create) create; exit;;
diff --git a/bin/ak-sm-filejoiner b/bin/ak-sm-filejoiner
--- a/bin/ak-sm-filejoiner
+++ b/bin/ak-sm-filejoiner
@@ -47,9 +47,12 @@ then
 
 	echo '#!/bin/bash' > script
 	
-	awk '{print "cp '$CHKDIR'/"$1" '$TMPWD'/"$2" "}' $MAPSDIR/$MAPSFILE| grep chk > script
+    # We create a script to copy all the chunks and rename them to their serialized
+    # name produced by split when we splitted the file
+	awk '{print "cp '$CHKDIR'/"$1" '$TMPWD'/"$2" "}' $MAPSDIR/$MAPSFILE| grep chk >> script
 
-	sh script
+	bash script
+
 	if [ "$?" != 0 ]
 	then
 		echo "Error executing copy script"
@@ -60,13 +63,22 @@ then
 	cd $TMPWD
 
 	echo "$PWD"
+    
+    # Final name we are going to rename to
 	OUTPUT="$(tail -n1 $MAPSDIR/$MAPSFILE | awk '{print $2}')"
 
 	echo $OUTPUT
 
+    # We grep the MAPSFILE for chk filenames in lines and we print them all in
+    # one line so the first `cat` will concatenate all chunks to OUTPUT
 	cat $(echo -n $(cat $MAPSDIR/$MAPSFILE|grep chk|awk '{print $2" "}'|tr -d '\n')) > $OUTPUT
 
+    # We check if everything is okay
 	sha512sum -c $MAPSDIR/$MAPSFILE
+    if [ "$?" != "0" ]; then
+        logit "[ERROR]" "Error while checking sums"
+        exit 1
+    fi
 	
 	mv $OUTPUT $CURDIR
 
diff --git a/bin/ak-sm-files b/bin/ak-sm-files
--- a/bin/ak-sm-files
+++ b/bin/ak-sm-files
@@ -4,6 +4,7 @@
 ZFILESDIR="$AK_WORKDIR/files"
 TEMP="/tmp/aktmp"
 PROGRAM="$(basename $0)"
+#set -xe
 logit(){
 	ak-logthis "<$PROGRAM>" "$1" "$2"
 }
@@ -17,7 +18,6 @@ if [ ! -d $ZFILESDIR ]; then
 		exit 1
 	fi
 	cd $ZFILESDIR
-	git init
 else
 	logit "[INFO]" "$ZFILESDIR found!"
 fi
@@ -39,6 +39,8 @@ tempassin(){
 
 usage(){
 	echo "$PROGRAM - file"
+    echo "  add <file>"
+    echo "  index"
 }
 
 add(){
@@ -53,6 +55,7 @@ main(){
     echo "Adding $FILENAME"
     logit "[INFO]" "Switching to tmp folder..."
     TEMPASSIN="$(tempassin)"
+
     cd $TEMPASSIN
     if [ $? == 0 ]; then
 	    logit "[INFO]" "Success"
@@ -61,6 +64,7 @@ main(){
 	    exit 5
     fi
     logit "[INFO]" "Copying $1 to $TEMPASSIN"
+
     cp $2/$1 $TEMPASSIN/$1
     if [ $? == 0 ]; then
 	    logit "[INFO]" "Copied successfully"
@@ -77,6 +81,15 @@ main(){
     else
 	    logit "[ERROR]" "Error in adding the $FILE to IPFS"
     fi
+
+    logit "[INFO]" "Adding $FILE to SHAMAPSYS..."
+    FILEMAP_SHA512_HASH=$(ak-sm-filesplitter $FILE)
+    if [ $? == 0 ]; then
+	    logit "[INFO]" "Added $FILE to SHAMAPSYS"
+    else
+	    logit "[ERROR]" "Error in adding the $FILE to SHAMAPSYS"
+    fi
+
     logit "[INFO]" "Signing..."
     SIGN_FILE=$FILENAME".asc"
     gpg2 --detach-sign --sign-with $FINGERPRINT --armor --output $SIGN_FILE $FILE
@@ -94,10 +107,20 @@ main(){
 	    logit "[ERROR]" "Error while adding"
     fi
 
+    logit "[INFO]" "Adding signature to SHAMAPSYS"
+    SHAMAPSIGMAP=$(ak-sm-filesplitter $TEMPASSIN/$SIGN_FILE)
+    if [ $? == 0 ]; then
+	    logit "[INFO]" "Added"
+    else
+	    logit "[ERROR]" "Error while adding"
+    fi
+
     cat > $TEMPASSIN/data <<EOF
 {
     "timestamp":"$(date -u +%s)",
     "filename":"$FILENAME",
+    "shamap":"$FILEMAP_SHA512_HASH",
+    "shamapsigmap":"$SHAMAPSIGMAP",
     "ipfs":"$FILE_IPFS_HASH",
     "detach":"$SIGNATURE"
 }
@@ -107,7 +130,7 @@ echo "Printing data..."
 cat $TEMPASSIN/data
 echo "Publishing..."
 
-    ak-pack_z_block files/add data
+    ak-pack_z_block sha-files/announce data
     if [ $? == 0 ]
     then
 	    echo "cool"
@@ -117,10 +140,16 @@ echo "Publishing..."
     fi
 }
 
+
+index(){
+    tail -n1 $AK_WORKDIR/fmp/* | grep '^[abcdef1234567890]' | awk '{ print $2 }'
+}
+
 if [ ! -z $1 ]; then
 	case $1 in
 		help) usage; exit;;
 		add) add $2; exit;;
+        index) index; exit;;
 		*) usage; exit;;
 	esac
 else usage
