Workaround for IPNS unresolvable zchain links
- Adds a "zlatest" field to the configuration of the node
- We update and publish the configuration each time we change the latest
  block of our zchain

diff --git a/bin/ak-pack_z_block b/bin/ak-pack_z_block
--- a/bin/ak-pack_z_block
+++ b/bin/ak-pack_z_block
@@ -145,6 +145,12 @@ then
         logit "[ERROR]" "Could not copy $ZBLOCK to /zlatest"
         exit 1
     fi
+    ak-config publish
+    if [ "$?" -ne 0 ]
+    then
+        logit "[ERROR]" "Could not publish new configuration"
+        exit 1
+    fi
 else
 	usage
 	exit 0
diff --git a/bin/ak-zchain-rebase b/bin/ak-zchain-rebase
--- a/bin/ak-zchain-rebase
+++ b/bin/ak-zchain-rebase
@@ -40,6 +40,12 @@ rebase (){
     ak-ipfs-name-publish --key=zchain /ipfs/$(cat $AK_ZLATEST)
     if [ $? != 0 ]; then exit 1; fi
 
+    ak-config publish
+    if [ "$?" -ne 0 ]
+    then
+        logit "[ERROR]" "Could not publish new configuration"
+        exit 1
+    fi
     echo "Rebase was successful"
     exit 0
 }
diff --git a/bin/ak-zchain-reset b/bin/ak-zchain-reset
--- a/bin/ak-zchain-reset
+++ b/bin/ak-zchain-reset
@@ -38,6 +38,13 @@ reset (){
 	echo "Publishing new (reset) ZLATEST"
 	ak-ipfs-name-publish --key=zchain /ipfs/$(cat $ZLATEST)
 	if [ $? != 0 ]; then exit 1; fi
+
+    ak-config publish
+    if [ "$?" -ne 0 ]
+    then
+        logit "[ERROR]" "Could not publish new configuration"
+        exit 1
+    fi
 	
 	echo "Reset was successful"
 	exit 0
