Making sure we get the return codes and display appropriate messages wherever needed

diff --git a/bin/ak-zblock-cache b/bin/ak-zblock-cache
--- a/bin/ak-zblock-cache
+++ b/bin/ak-zblock-cache
@@ -16,11 +16,20 @@ then
             ak-zblock-show "$1" > $AK_ZBLOCKDIR/$1
         fi
         logit "[INFO]" "No cache found. Caching..."
+        ak-zblock-show "$1" 
+        if [ "$?" -ne "0" ]
+        then
+            logit "[ERROR]" "ak-zblock-show failed..."
+            exit 1
+        fi
         ak-zblock-show "$1" > $AK_ZBLOCKDIR/$1
+    else
+        logit "[ERROR]" "Could not find zblock $1..."
+        exit 1
     fi
     exit 0
 else
-    echo not ok
+    printf "Usage:\n\t%s <zblock-ipfs-hash>\n" "$PROGRAM" 1>&2
     exit 1
 fi
 
